### ISSUE TITLE
Talent can not receive subscribed data from vss server

### ISSUE THREAD

**Issue by wenwenchenbosch** [GENIVI/iot-event-analytics#81]
I tried out the kuksa.val integration example using [kuksa.val@2f3afd96fe](https://github.com/eclipse/kuksa.val/tree/2f3afd96fe7488dde55802ebf97b4f1435f9f8a3) 

I can not understand, why talents can only received event for signal Acceleration$Longitudinal, which the example published to vss server, but if I changed the rule from

https://github.com/GENIVI/iot-event-analytics/blob/7f757ae658a1ff02f017ef34b8cf01f5b32b1bd5/src/sdk/javascript/examples/integrations/kuksa.val/index.js#L54-L58

to

``` 
new Rule(new OpConstraint('Acceleration$Lateral', OpConstraint.OPS.ISSET, null, 'Vehicle', VALUE_TYPE_RAW))
```

No events can be received in the `onEvent` function:
https://github.com/GENIVI/iot-event-analytics/blob/7f757ae658a1ff02f017ef34b8cf01f5b32b1bd5/src/sdk/javascript/examples/integrations/kuksa.val/index.js#L60-L70

But I see in the log, that data received via `subscribe`:
```
2021-05-25T17:54:36.153Z    INFO [KuksaValDemo] : Received 222 from Vehicle.Acceleration.Lateral
```

Actually, I am not sure, what is the meaning of the `to.addFor` line, there seems to be no effect and also no docu found for this function.

**Comment by llakie** [comment]
The addFor method allows setting values outside the namespace of your talent.

**Comment by llakie** [comment]
I will work on the integration example and make it working again. #71

**Comment by llakie** [comment]
I fixed the wrong DNS name of the Kuksa.VAL server in [docker-compose.kuksa.val2iotea.yml](https://github.com/GENIVI/iot-event-analytics/blob/develop/src/sdk/javascript/examples/integrations/kuksa.val/docker-compose.kuksa.val2iotea.yml). Now it's working. Please make sure, that you are referencing an existing Kuksa.VAL image in your local registry [here](https://github.com/GENIVI/iot-event-analytics/blob/develop/src/sdk/javascript/examples/integrations/kuksa.val/.env). Make sure you have a correct vss.json and your certificates are up to date in [this](https://github.com/GENIVI/iot-event-analytics/tree/develop/src/sdk/javascript/examples/integrations/kuksa.val/config/kuksa.val) folder. Update the JSON WebToken in the kuksa.val2iotea adapter [here](https://github.com/GENIVI/iot-event-analytics/blob/develop/src/sdk/javascript/examples/integrations/kuksa.val/config/kuksa.val2iotea/config.json).
With this prerequisites done, everything should work fine.

The example works as following:
- `Vehicle.Acceleration.Longitudinal` is sent to Kuksa.VAL periodically
- The Talent subscribes on this data point
- The Kuksa.val2iotea adapter subscribes at Kuksa.VAL for this data point and receives updates from Kuksa.VAL + forwards it to IoT Event Analytics
- The talent sets `Vehicle.Acceleration.Lateral` in the IoT Event Analytics Platform
- The Kuksa.val2iotea adapter transfers this value to Kuksa.VAL, where it is updated.

**Comment by llakie** [comment]
Will be fixed in #99

**Comment by SebastianSchildt** [comment]
@wenwenchenbosch  @nayakned can you check?

**Comment by wenwenchenbosch** [comment]
@JochenKienzle I would like to reopen this issue, because I think this one is still not fixed. 
The [develop branch from today](https://github.com/GENIVI/iot-event-analytics/tree/e22e525c5b5b8e6eeb888afea094762308398050) works even worse. 

After changing the type from `number` to `string`, the following talent can still not receive signal from `kuksa.val`:
https://github.com/GENIVI/iot-event-analytics/blob/dd3b2bed465f087da6f5e100faf7dbdd6e3497f4/src/sdk/javascript/examples/integrations/kuksa.val/config/platform/types.json#L19

But, we checked the old commit [45f8ba229af1a5d27b64f64f3973263a777d7ed7](https://github.com/GENIVI/iot-event-analytics/tree/45f8ba229af1a5d27b64f64f3973263a777d7ed7), it was working.

**Comment by wenwenchenbosch** [comment]
I made mistake. I tested the integration test with the wrong kuksa.val version. Using amd64/kuksa-val:98f961b, everything works fine. (I see some signal loop issues, but I can not reproduce it. I will create another ticket, if I can reproduced the loop issues.)

But because kuksa-val:98f961b is just a commit and it is not possible to download the image anymore. It will be better to be compatible with a getagged kuksa-val version. A new ticket #105 is created for it. This ticket can keep close.
